/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void set_mode(int,int *,int);
void led_on(int,int *,int);
void led_off(int,int *,int);
void delay(int);


int main(void)
{
	int RCC = 0x40023800;
	int *RCC_ABH1ENR = (int *)(RCC + 0x30);

	*RCC_ABH1ENR |= (1 << 0);

	int GPIOA = 0X40020000;
	int *GPIOA_MODE = (int *)(GPIOA + 0X00);
	int *GPIOA_ODR = (int *)(GPIOA + 0x14);

	set_mode(1,GPIOA_MODE,10);

	while(1)
	{
		led_on(1,GPIOA_ODR,5);
		delay(5);
		led_off(1,GPIOA_ODR,5);
		delay(5);
	}
}

void set_mode(int logic,int *GPIOA_MODE,int bit)
{
	*GPIOA_MODE |= (logic << bit);
}

void delay(int time)
{
	for(;time > 0;time--)
	{
		for(int i=0;i < 754300;i++)
		{
		}
	}
}

void led_on(int logic,int *GPIOA_ODR,int bit)
{
	*GPIOA_ODR |= (logic << bit);
}

void led_off(int logic,int *GPIOA_ODR,int bit)
{
	 *GPIOA_ODR &= ~(logic << bit);
}
