/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	int *rcc = (int *)(RCC_AHB1ENR);

	*rcc |= (1 << 0);

	int *gpio_mode = (int *)(GPIOA_MODE);
	int *gpio_odr = (int *)(GPIOA_ODR);

	set_mode(1,gpio_mode,10);

	while(1)
	{
		led_on(1,gpio_odr,5);
		delay(5);
		led_off(1,gpio_odr,5);
		delay(5);
	}
}

void set_mode(int logic,int *mode,int bit)
{
	*mode |= (logic << bit);
}

void delay(int time)
{
	for(;time > 0;time--)
	{
		for(int i=0;i < 754300;i++)
		{
		}
	}
}

void led_on(int logic,int *odr,int bit)
{
	*odr |= (logic << bit);
}

void led_off(int logic,int *odr,int bit)
{
	 *odr &= ~(logic << bit);
}
